### ISSUE TITLE
Which gem/repository to use?

### ISSUE THREAD

**Issue by rstammer** [clbustos/distribution#28]
Dear @clbustos, 

Thanks for your work on the awesome gem `distribution`!

I'd like to use the gem for some projects but I'm a bit confused about the future: This repository,  the original `clbustos/distribution`, references the SciRuby-Fork as its homepage (See [here in the gemspec](https://github.com/clbustos/distribution/blob/master/distribution.gemspec#L10)). Also, the SciRuby-Fork, ([sciruby/distribution](https://github.com/sciruby/distribution)) contains some constructive work that is not contained in the original, and, confusingly, vice versa, the original contains some work (from 2019) that is not in the Sciruby-fork.

So, of course I completely understand how we may run into this, but I'm asking myself: Shall we invest some work to bring these two forks together again? If yes, what should be the "common" place to continue development? As you are also member of `SciRuby`: Should it be the original repository, this one or should it be where the `SciRuby`-fork lives?  So, would it be good 
to investing work to move the work contained in sciruby/distribution into this one, or would it be good trying to get the work of clbustos/distribution into Sciruby? 

Thanks in advance!

**Comment by clbustos** [comment]
Hi, @neumanrq . 
Thanks for you support. 

I developed statsample and all related projects, like distribution, as a personal project. Later, circa 2012-2013, Sciruby people ask me to join their effort and provide my libraries as a foundation for statistical related work. 

So,  SciRuby provides the official version for distribution. Anyway, as long they maintains the broad orientations of the projects, when I have some spare time I update the tests and try to add something valuable, but is not official until SciRuby pull my commits.
